"""remove_rush_mode

Revision ID: e54bfa48d23f
Revises: fc09e9fdd313
Create Date: 2026-02-28 20:47:45.737785+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e54bfa48d23f'
down_revision: Union[str, None] = 'fc09e9fdd313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rush_puzzles')
    with op.batch_alter_table('rush_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_rush_sessions_user_id')

    op.drop_table('rush_sessions')
    with op.batch_alter_table('rush_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_rush_attempts_session_id')

    op.drop_table('rush_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rush_attempts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('puzzle_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_answer', sa.VARCHAR(length=500), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('time_taken_ms', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['rush_puzzles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['rush_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rush_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_rush_attempts_session_id', ['session_id'], unique=False)

    op.create_table('rush_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('current_score', sa.INTEGER(), nullable=False),
    sa.Column('current_streak', sa.INTEGER(), nullable=False),
    sa.Column('max_streak', sa.INTEGER(), nullable=False),
    sa.Column('lives_remaining', sa.INTEGER(), nullable=False),
    sa.Column('start_rating', sa.FLOAT(), nullable=False),
    sa.Column('rating_change', sa.FLOAT(), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rush_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_rush_sessions_user_id', ['user_id'], unique=False)

    op.create_table('rush_puzzles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('difficulty', sa.INTEGER(), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('explanation', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
