"""add_rating_fields_to_user

Revision ID: da39a8f3aa76
Revises: c29d4d1b2927
Create Date: 2026-02-23 21:08:30.915632+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da39a8f3aa76'
down_revision: Union[str, None] = 'c29d4d1b2927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('old_rating', sa.Float(), nullable=False),
    sa.Column('new_rating', sa.Float(), nullable=False),
    sa.Column('rating_change', sa.Float(), nullable=False),
    sa.Column('old_deviation', sa.Float(), nullable=False),
    sa.Column('new_deviation', sa.Float(), nullable=False),
    sa.Column('context', sa.String(length=20), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classical_rd', sa.Float(), nullable=False, server_default='350.0'))
        batch_op.add_column(sa.Column('blitz_rd', sa.Float(), nullable=False, server_default='350.0'))
        batch_op.add_column(sa.Column('volatility', sa.Float(), nullable=False, server_default='0.06'))
        batch_op.alter_column('classical_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('blitz_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('blitz_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('classical_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('volatility')
        batch_op.drop_column('blitz_rd')
        batch_op.drop_column('classical_rd')

    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_history_user_id'))

    op.drop_table('rating_history')
    # ### end Alembic commands ###
